# Generated by Django 3.2.5 on 2021-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('text', models.TextField(help_text='Напишите текст', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.CharField(help_text='Укажите автора', max_length=200, verbose_name='Автор')),
                ('group', models.CharField(help_text='Дайте название группе', max_length=200, verbose_name='Группа')),
            ],
        ),
    ]
