# Generated by Django 3.2.7 on 2021-09-18 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('to_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.CharField(blank=True, max_length=10, null=True)),
                ('visa_id', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нужна виза'), (1, 'Виза не нужна'), (2, 'У меня есть шенген')], null=True)),
                ('covid_status', models.PositiveSmallIntegerField(choices=[(0, 'Нет ограничений'), (1, 'Закрыт или ограничен въезд для пассажиров, побывавших в определенных странах'), (2, 'Въезд запрещен')], default=0)),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
                'db_table': 'summaries_destinations',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_feedback', models.IntegerField(choices=[(1, 'published'), (2, 'not published')], null=True)),
                ('user_feedback_timestamp', models.DateTimeField(null=True)),
                ('user_photo', models.TextField(blank=True, max_length=256, null=True)),
                ('user_photo_timestamp', models.DateTimeField(null=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('icon', models.ImageField(upload_to='reservations/icons', verbose_name='Иконка')),
                ('logo', models.ImageField(upload_to='reservations/logos', verbose_name='Логотип')),
                ('link', models.CharField(max_length=300, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'reserverions_reservations',
            },
        ),
    ]
