# Generated by Django 3.2.6 on 2021-08-31 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15, verbose_name='Номер обращения')),
                ('author', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('text', models.TextField(blank=True, default='', verbose_name='Описание проблемы')),
                ('photos', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=120)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100)),
                ('day', models.DateField()),
                ('reason', models.CharField(choices=[('unk', 'Не известно'), ('R_t', 'Не хватило времени'), ('R_f', 'Форс-мажор'), ('R_i', 'Техническая проблема')], default='unk', max_length=3)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
