# Generated by Django 3.2.7 on 2021-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('open', 'Открыт'), ('closed', 'Закрыт')], default='new', max_length=6)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_cash_only', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
